sudo: required
language: go
services: docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

after_success:
  - |
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker version
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker build -t jackytck/rabbit-go-file-docker:v0.0.5 .
      docker push jackytck/rabbit-go-file-docker:v0.0.5
    fi
