sudo: required
language: go
services: docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

after_success:
  - |
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker version
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker build -t jackytck/rabbit-go-file-docker:v0.0.3 .
      docker push jackytck/rabbit-go-file-docker:v0.0.3
    fi
